Repository Year4-S1/SSD_Web_Backend, pull requests merged in 2022-11, with the labels that each got.

#1 created user registration by IT19136134
  package-lock.json
  package.json
  server.js
  src/controllers/user-controller.js
  src/enums/user-enum.js
  src/log/log.js
  src/middleware/authentication.js
  src/models/user-model.js
  src/response/response-handler.js
  src/routes.js
  src/services/user-service.js
Labels: enhancement

#2 implemented user login by IT19136134
  src/controllers/user-controller.js
  src/services/user-service.js
Labels: enhancement

#3 It19146652/raveena
  package-lock.json
  package.json
  src/controllers/message-controller.js
  src/enums/message-enums.js
  src/models/message-model.js
  src/routes.js
  src/services/message-service.js
Labels: enhancement

#4 modifications to user model and user service by IT19136134
  src/middleware/authentication.js
  src/models/user-model.js
  src/services/user-service.js
Labels: enhancement

#5 implemented update password , modified authentication and solved bug in createuser by IT19136134
  src/controllers/user-controller.js
  src/middleware/authentication.js
  src/services/user-service.js
Labels: bug, enhancement

#6 It19146652/raveena
  package-lock.json
  package.json
  src/controllers/message-controller.js
  src/enums/message-enums.js
  src/middleware/authentication.js
  src/routes.js
  src/services/message-service.js
Labels: enhancement

#7 implemented getalluser and getuserbyid methods by IT19136134
  src/controllers/user-controller.js
  src/services/user-service.js
Labels: enhancement

#9 implemented file upload and retrieve files by userId by IT19136134
  package-lock.json
  package.json
  server.js
  src/controllers/file-controller.js
  src/enums/file-enums.js
  src/models/file-model.js
  src/routes.js
  src/services/file-service.js
Labels: enhancement

#10 It19146652/raveena
  src/controllers/message-controller.js
  src/enums/message-enums.js
  src/services/message-service.js
Labels: enhancement, api, backend

#11 implemented the tls and user access control by IT19136134
  index.html
  package-lock.json
  package.json
  server.crt
  server.csr
  server.js
  server.key
  src/controllers/user-controller.js
  src/middleware/authentication.js
  src/routes.js
  src/services/file-service.js
  src/services/user-service.js
Labels: enhancement, backend

#12 modification of token time by IT19136134
  src/controllers/file-controller.js
  src/controllers/user-controller.js
  src/routes.js
  src/services/file-service.js
  src/services/user-service.js
Labels: enhancement, backend

#22 imlpemented cipher encryption and decryption for file url storage by IT19136134
  package-lock.json
  package.json
  src/models/file-model.js
  src/services/file-service.js
  src/services/user-service.js
Labels: enhancement, backend

#24 It19146652/raveena
  package-lock.json
  package.json
  src/models/message-model.js
  src/services/message-service.js
Labels: enhancement, api, backend
